name: itrue-qt-imx-hello-world
base: core20
version: '0.1'
summary: Example application for showing how to use Qt from another snap
description: |
  Example application for showing how to use Qt from another snap for the i.MX
  6 & 8 SoCs. This uses itrue-qt-imx-snap as a base.

grade: devel
confinement: devmode

plugs:
  gpu:
    interface: custom-device

parts:
  qt5:
    plugin: nil
    source: .
    build-packages:
      - squashfs-tools
    override-build: |
      unsquashfs -d ${SNAPCRAFT_PART_INSTALL}/ -f \
        ${SNAPCRAFT_PROJECT_DIR}/itrue-qt-imx-snap_5.6.3_${SNAPCRAFT_TARGET_ARCH}.snap
    stage:
      - -meta
      - -opt/hello-world
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/lib/cmake
      - -usr/bin/qmake
      - -usr/mkspecs
      - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/*.a
      - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/*.la

  hello-world:
    after:
      - qt5
    plugin: nil
    source: hello-world
    override-build: |
      ${SNAPCRAFT_PROJECT_DIR}/stage/usr/bin/qmake
      make -j$(nproc)
      make INSTALL_ROOT=${SNAPCRAFT_PART_INSTALL} install

apps:
  hello-world:
    command: opt/hello-world/bin/hello-world
    environment:
      QT_PLUGIN_PATH: $SNAP/usr/plugins
    plugs:
      - opengl
      - hardware-observe
      - framebuffer
      - gpu

layout:
  /etc/glvnd:
    bind: $SNAP/etc/glvnd
  /usr/share/X11/xkb:
    bind: $SNAP/usr/share/X11/xkb
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/glvnd:
    bind: $SNAP/usr/share/glvnd
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
  /usr/lib/fonts:
    bind: $SNAP/usr/lib/fonts
